config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  resources :entities do
    resources :entity_fields
    resources :entity_rows
    resources :entity_values
    resources :entity_graphs
  end
end

app/models/entity_field.rb
class EntityField < ApplicationRecord
  belongs_to :entity

  has_many :entity_values, dependent: :destroy
  has_many :entity_graphs, dependent: :destroy

  validates :title, presence: true
  validates :field_type, presence: true

  scope :field_types, -> { FIELD_TYPES }

  def is_primary_field? = entity.primary_field_id == id

  FIELD_TYPES = [
    'string',
    'number'
  ]
end

app/controllers/entity_fields_controller.rb
class EntityFieldsController < ApplicationController
  before_action :get_entity, only: [:create, :destroy, :edit, :update]
  before_action :get_entity_field, only: [:destroy, :edit, :update]

  def create
    @entity_field = @entity.entity_fields.new(entity_field_params)

    if @entity_field.save
      redirect_to entity_path(@entity)
    else
      redirect_to entity_path(@entity, error: 'Unable to add field')
    end
  end

  def destroy
    @entity.clear_primary_field if @entity_field.is_primary_field?

    @entity_field.destroy
    redirect_to entity_path(@entity), status: 303
  end

  def edit; end

  def update
    @entity_field.update(entity_field_params)
    redirect_to entity_path(@entity)
  end

  private

  def entity_field_params = params.require(:entity_field).permit(:title, :field_type)
  def get_entity = @entity = Entity.find(params[:entity_id])
  def get_entity_field = @entity_field = EntityField.find(params[:id])
end

app/helpers/entity_fields_helper.rb
module EntityFieldsHelper
end

app/views/entity_fields/_new_form.html.haml
.box.is-fullheight
  %h2.title.is-4 Add Field
  = form_with model: [ @entity, @entity.entity_fields.build ] do |form|
    .field
      = form.label :title, class: 'label'
      .control= form.text_field :title, class: 'input'
    .field
      = form.label :field_type, class: 'label'
      .control
        .select.is-fullwidth
          = form.select :field_type, EntityField.field_types
    = form.submit 'Save', class: 'button'

app/views/entity_fields/edit.html.haml
= link_to ('<i class="fas fa-arrow-left"></i>').html_safe, @entity, class: 'button is-text block'

.box.block.has-restricted-width
  = form_with model: @entity_field, url: entity_entity_field_path do |form|
    .field
      = form.label :title, class: 'label'
      .control= form.text_field :title, class: 'input'
    = form.submit 'Save', class: 'button'