config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  resources :entities do
    resources :entity_fields
    resources :entity_rows
    resources :entity_values
    resources :entity_graphs
  end
end

app/models/entity.rb
class UnpopulatedRowError < StandardError; end

class Entity < ApplicationRecord
  has_many :entity_fields, dependent: :destroy
  has_many :entity_rows, dependent: :destroy
  has_many :entity_values, dependent: :destroy
  has_many :entity_graphs, dependent: :destroy
  has_one :primary_field, class_name: 'EntityField', primary_key: :primary_field_id, foreign_key: :id

  validates :title, presence: true
  before_destroy :clear_primary_field, prepend: true

  def clear_primary_field = update_attribute(:primary_field_id, nil)

  def update_row(row: nil, values_by_field: {})
    # Validate input is present and is associated with at least one field on this entity
    raise UnpopulatedRowError if values_by_field.values.length == 0
    raise UnpopulatedRowError unless entity_fields.any? {|field| values_by_field[field.title]}

    transaction do # Start a transaction so we can roll back if any values fail
      row = entity_rows.create! unless row # Create the row if needed

      entity_fields.each do |field| # For each field, attempt to update a value for the row
        value = values_by_field[field.title]
        next unless value # If no value has been submitted for this field, skip this iteration

        input = { entity_id: id, entity_field_id: field.id, entity_row_id: row.id }
        entity_value = EntityValue.find_by **input # Load the EntityValue for this field and row

        if entity_value and value.length == 0
          entity_value.destroy # If the value exists and new value is blank, clear it
        elsif entity_value
          entity_value.update! value: value # If we've found an EntityValue, update it
        elsif value.length > 0
          EntityValue.create! **input, value: value # Otherwise, make a new one
        end
      end

      # Validate there are still values for this row - cancel transaction if not
      values_for_row = EntityValue.where(entity_row_id: row.id)
      raise UnpopulatedRowError if values_for_row.length == 0

      row # Return the updated row
    end
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :get_entity, only: [:show, :edit, :update, :destroy]

  def index = @entities = Entity.all

  def show; end

  def new = @entity = Entity.new

  def create
    @entity = Entity.new(entity_params)

    if @entity.save
      redirect_to entities_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @entity.update(entity_params)
      redirect_to @entity
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @entity.destroy
    redirect_to entities_path, status: 303
  end

  private

  def entity_params = params.require(:entity).permit(:title, :primary_field_id)
  def get_entity = @entity = Entity.find(params[:id])
end

app/helpers/entities_helper.rb
module EntitiesHelper
  def all_entities
    Entity.all
  end

  def entity_values_by_row_and_field(entity)
    # Get prerequisite data
    fields = entity.entity_fields
    rows = entity.entity_rows
    values = entity.entity_values

    # Build structure
    rows_array = rows.each.map do |row|
      fields_array = fields.each.map do |field|
        value = values.find { |value| value.entity_field_id == field.id and value.entity_row_id == row.id }
        display_value = ''
        display_value = value.value if value

        [field.title, display_value]
      end
      [row.id, fields_array.to_h]
    end
    rows_array.to_h
  end
end

app/views/entities/_entity_table.html.haml
.box
  = render 'shared/data_table', fields: @entity.entity_fields, data: entity_values_by_row_and_field(@entity) do |row_id|
    = link_to ('<i class="fas fa-pen"></i>').html_safe,
      edit_entity_entity_row_path(@entity, row_id),
      class: 'button is-text is-small'

    = link_to ('<i class="fas fa-trash"></i>').html_safe,
      entity_entity_row_path(@entity, row_id),
      data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
      class: 'button is-small has-text-danger is-text'

app/views/entities/_form.html.haml
= form_with model: @entity,
  data: { turbo_frame: '_top' } do |form|
  .field
    = form.label :title, class: 'label'
    .control= form.text_field :title, class: 'input'
    - @entity.errors.full_messages_for(:title).each do |message|
      = message
  - if @entity.entity_fields.length > 0
    .field
      = form.label :primary_field_id, class: 'label'
      .control
        .select.is-fullwidth= form.select :primary_field_id, @entity.entity_fields.map {|f| [f.title, f.id]}
      - @entity.errors.full_messages_for(:primary_field_id).each do |message|
        = message
  = form.submit 'Save', class: 'button'

app/views/entities/edit.html.haml
= turbo_frame_tag 'edit-entity' do
  .box.block.has-restricted-width.mb-5.ml-auto.is-relative
    = link_to ('<i class="fas fa-times"></i>').html_safe,
      @entity, class: 'button is-text is-small is-rounded close-button'
    = render 'form', entity: @entity

app/views/entities/index.html.haml
%h1.title Entities

= turbo_frame_tag 'entities_list', target: '_top' do
  .columns.mb-2.is-multiline
    - @entities.each do |entity|
      .column.is-6-tablet.is-4-desktop.is-3-widescreen
        .card
          .card-content.has-background-white-bis
            %h2.title.has-text-centered.is-4= entity.title
          .card-footer
            = link_to ('<i class="fas fa-eye"></i>').html_safe,
              entity_path(entity), class: 'card-footer-item'

  = turbo_frame_tag 'new_entity' do
    = link_to 'New', new_entity_path, class: 'button'

app/views/entities/new.html.haml
= turbo_frame_tag 'new_entity' do

  .box.block.has-restricted-width.is-relative
    = link_to ('<i class="fas fa-times"></i>').html_safe,
      @entity, class: 'button is-text is-small is-rounded close-button'
    = render 'form', entity: @entity

app/views/entities/show.html.haml
- if params[:error]
  .notification.is-danger= params[:error]

= turbo_frame_tag 'edit-entity' do
  .is-clearfix
    %h1.title.is-pulled-left= @entity.title
    - if @entity.primary_field
      %p.is-pulled-left.p-2
        Primary field:
        = @entity.primary_field.title

    .is-pulled-right
      = link_to ('<i class="fas fa-pen"></i>').html_safe,
        edit_entity_path(@entity),
        class: 'button is-small is-text'

      = link_to ('<i class="fas fa-trash"></i>').html_safe,
        entity_path(@entity),
        data: { turbo_method: :delete, turbo_confirm: "Are you sure?", turbo_frame: '_top' },
        class: 'button is-small has-text-danger is-text'

= render 'entity_table', entity: @entity

.columns.is-multiline
  .column.is-full.is-one-third-widescreen= render 'entity_rows/new_form', entity: @entity
  .column.is-full.is-one-third-widescreen= render 'entity_fields/new_form', entity: @entity
  .column.is-full.is-one-third-widescreen= render 'entity_graphs/new_form', entity: @entity

- if @entity.entity_graphs.length > 0
  .columns.is-multiline
    - @entity.entity_graphs.each do |graph|
      - if graph.id
        .column.is-full.is-half-widescreen= render graph