config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  resources :entities do
    resources :entity_fields
    resources :entity_rows
    resources :entity_values
    resources :entity_graphs
  end
end

app/views/shared/_data_table.html.haml
/ Expected data structure:
/ fields: [{ title: 'Example' }]
/ data: {1: {'Example': 'Hello'}, 2: {'Example': 'Row 2'}}

- if data.length > 0
  %div{ data: {
    controller: 'table',
    table_sort_field_value: '',
    table_sort_direction_value: 'asc',
    table_no_sort_class: 'fa-sort',
    table_sort_asc_class: 'fa-sort-down',
    table_sort_desc_class: 'fa-sort-up'
  }}
    .field
      .control
        %input.input.table-search{placeholder: 'Filter...', data: { action: 'table#updateFilter' }}
    %table.table.is-fullwidth{ data: { table_target: 'table' }}
      %thead
        %tr
          - fields.each do |field|
            %th.has-text-left
              = field.title
              %button.button.is-pulled-right.is-small.is-text{ data: {
                sort_field: field.title,
                action: 'table#updateSort'
              }}
                %i.fas.fa-sort{ data: { table_target: 'sortIcon', sort_field: field.title }}

          %th
      %tbody{ data: { table_target: 'body' }}
        - data.each do |row_id, row|
          %tr{ data: { table_target: 'row' }}
            - fields.each do |field|
              %td{ data: { value: row[field.title], field: field.title }}
                = row[field.title]
            %td.has-text-right.action-cell
              = yield row_id
- else
  = render 'shared/not_found_message', object: 'rows'

app/views/shared/_not_found_message.html.haml
%p.is-fullwidth.has-text-centered.has-text-grey.is-size-4 No #{object} found

app/views/shared/_sidebar.html.haml
%div{ data: { controller: 'sidebar', sidebar_closed_class: 'is-hidden-mobile' }}
  %button.button.is-hidden-tablet{ data: { action: 'sidebar#toggle' }} Menu
  %aside.menu.mt-4.is-hidden-mobile{ data: { sidebar_target: 'sidebar' }}
    %p.menu-label= link_to 'Dashboard', root_path, class: 'has-text-black'
    %ul.menu-list
      %li
        = link_to 'Entities', entities_path, class: active_page(entities_path)
        %ul
          - all_entities.each do |entity|
            %li= link_to entity.title, entity, class: active_page(entity)