config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  resources :entities do
    resources :entity_fields
    resources :entity_rows
    resources :entity_values
    resources :entity_graphs
  end
end

app/models/entity_row.rb
class EntityRow < ApplicationRecord
  belongs_to :entity

  has_many :entity_values, dependent: :destroy
end

app/controllers/entity_rows_controller.rb
class EntityRowsController < ApplicationController
  before_action :get_entity, only: [:create, :destroy, :edit, :update]
  before_action :get_entity_row, only: [:destroy, :edit, :update]

  def create
    begin
      @entity.update_row(values_by_field: params[:entity_row].delete_if {|key, val| val.length == 0})
    rescue UnpopulatedRowError
      redirect_to entity_path(@entity, error: 'Unable to add row: row must have at least one value')
    else
      redirect_to entity_path(@entity)
    end
  end

  def destroy
    @entity_row.destroy
    redirect_to entity_path(@entity), status: 303
  end

  def edit; end

  def update
    begin
      @entity.update_row(row: @entity_row, values_by_field: params[:entity_row])
    rescue UnpopulatedRowError
      redirect_to entity_path(@entity, error: 'Unable to edit row: row must have at least one value')
    else
      redirect_to entity_path(@entity)
    end
  end

  private

  def get_entity = @entity = Entity.find(params[:entity_id])
  def get_entity_row = @entity_row = EntityRow.find(params[:id])
end

app/helpers/entity_rows_helper.rb
module EntityRowsHelper
end

app/views/entity_rows/_new_form.html.haml
.box.is-fullheight
  %h2.title.is-4 Add Row
  - if @entity.entity_fields.length > 0
    = form_with model: [@entity, @entity.entity_rows.build] do |form|
      - @entity.entity_fields.each do |field|
        .field
          = form.label field.title, class: 'label is-pulled-left'

          .is-pulled-right
            = link_to ('<i class="fas fa-pen"></i>').html_safe,
              edit_entity_entity_field_path(@entity, field),
              class: 'button is-text is-small'

            = link_to ('<i class="fas fa-trash"></i>').html_safe,
              entity_entity_field_path(@entity, field),
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
              class: 'button is-small has-text-danger is-text'

          .control
            - if field.field_type == 'string'
              = form.text_field field.title, class: 'input'
            - elsif field.field_type == 'number'
              = form.number_field field.title, class: 'input'
      = form.submit 'Save', class: 'button'
  - else
    = render 'shared/not_found_message', object: 'fields'

app/views/entity_rows/edit.html.haml
= link_to ('<i class="fas fa-arrow-left"></i>').html_safe, @entity, class: 'button is-text block'

.box.block.has-restricted-width
  = form_with model: @entity_row, url: entity_entity_row_path do |form|

    - @entity.entity_fields.each do |field|
      .field
        = form.label field.title, class: 'label'
        .control
          = form.text_field field.title, class: 'input', value: display_value_by_field_and_row(field: field, row: @entity_row)

    = form.submit 'Save', class: 'button'